remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: San Alberto 2025
description: Aqui podr√°s encontrar todas las bases de los torneos, horarios y localizaciones de los torneos de  de San Alberto 2025!
